### ISSUE TITLE
How do I fail to commit

### ISSUE THREAD

**Issue by gavin-yeh** [go-courier/husky#10]
Add exit 1 to my yaml file in hook

``` yaml
hooks:
  pre-commit:
    - exit 1
```

But no effect
How do I fail to submit?
